source 'http://rubygems.org'

# All environments.
gem 'rails', '3.0.9'
gem 'sqlite3'
gem "haml-rails"
gem "compass"

group :development, :test do
  gem "factory_girl_rails"
  gem "rails3-generators"
  gem "ruby-debug19"
  gem 'spork', '>=0.9.0.rc7'
  gem 'guard'
  gem 'guard-spork'
  gem 'growl'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'rb-fsevent'
end                   

group :test do
  gem "rspec-rails"
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
  gem "mocha"
end

